### ISSUE TITLE
Model Names

### ISSUE THREAD

**Issue by namper** [shotttik/carwashProject#1]
მოდელის კლასის დარქმევისას Model დაბოლოვება არაა კარგი პრაქტიკა 
ორმ-შიც მერე უფრო ლამაზია როცა წერ მაგ `User.objects.all()` განსხვავებით `UserModel.objects.all()`

**Comment by shotttik** [comment]
მადლობა. შევასწორე, გავითვალისწინებ აუცილებლად.
