### ISSUE TITLE
Through model

### ISSUE THREAD

**Issue by namper** [shotttik/carwashProject#2]
https://github.com/shotttik/carwashProject/blob/f27b94b197de05b8c1b73b1c4a367c87b1d1a6a2/carwash/models.py#L49

შუამავლი მოდელის მითითება აქ არაა აუცილებელი, თავისით აგებს ჯანგო, შუამავლის მითითება მაშინ გვინდა როცა კავშირებს შორის გვინდა მონაცემის შენახვა

**Comment by shotttik** [comment]
ოქეიი
